import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ingest, IngestWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Ingest.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
config :ingest, :openid_connect_oneid,
  issuer: "https://identity-preview.inl.gov",
  client_id: "",
  client_secret: "",
  redirect_uri: "http://localhost:4000/users/log_in/one_id",
  response_type: "code",
  scope: "openid email profile",
  ca_cert: "/etc/ssl/certs/CAINLROOT.cer"

config :ingest, :openid_connect_okta,
  issuer: System.get_env("OKTA_ISSUER"),
  client_id: System.get_env("OKTA_CLIENT_ID"),
  client_secret: System.get_env("OKTA_CLIENT_SECRET")
  redirect_uri: "#{System.get_env("PHX_HOST")}/users/log_in/okta",
  response_type: "code",
  scope: "openid email profile",
  ca_cert: "/etc/ssl/certs/CAINLROOT.cer"

config :ingest, :ca_certfile_path, "/etc/ssl/certs/CAINLROOT.cer"
